package integgre.ma_volvo.constanst

abstract class ConstanstFiles {

    companion object {
        val PREFERENCES_USER : String = "PREFERENCES_USER"

        val LOGIN_KEY_USER : String = "LOGIN_KEY_USER"
        val LOGIN_KEY_USER_CLIENT_ID : String = "LOGIN_KEY_USER_CLIENT_ID"
        val LOGIN_KEY_USER_ID : String = "LOGIN_KEY_USER_ID"
        val LOGIN_KEY_USER_NAME : String = "LOGIN_KEY_USER_NAME"
        val LOGIN_KEY_USER_IMEI : String = "LOGIN_KEY_USER_IMEI"
        val HOME_KEY_USER_BINNACLE : String = "HOME_KEY_USER_BINNACLE"
        val LOGIN_KEY_TERM_AND_COND : String = "LOGIN_KEY_TERM_AND_COND"
        val LOGIN_KEY_TERM_AND_COND_ONLY_READ : String = "LOGIN_KEY_TERM_AND_COND_ONLY_READ"
        val HOME_KEY_USER_TYPE : String = "HOME_KEY_USER_TYPE"
        val PROFILE_CLIENTE_IMG_URI : String = "PROFILE_CLIENTE_IMG_URI"
        val NOTIFICATION_FCM_MESSAGES_ARRAY : String = "NOTIFICATION_FCM_MESSAGES_ARRAY"
        val NOTIFICATION_FCM_COUNT : String = "NOTIFICATION_FCM_COUNT"
        val HOME_LAST_RES_ID_SHOW : String = "HOME_LAST_RES_ID_SHOW"
        val HOME_LAST_LIST_NEWS : String = "HOME_LAST_LIST_NEWS"
        val HOME_LAST_BRANCHS_ARRAY : String = "HOME_LAST_BRANCHS_ARRAY"
        val HOME_LAST_BRANCHS_LIST : String = "HOME_LAST_BRANCHS_LIST"
        val HOME_USER_POINTS : String = "HOME_USER_POINTS"
        val HOME_KEY_DIRECT_ACCESS : String = "HOME_KEY_DIRECT_ACCESS"
        val HOME_NOTIFICATION_MESSAGE : String = "HOME_NOTIFICATION_MESSAGE"
        val HOME_NOTIFICATION_MESSAGE_LAST : String = "HOME_NOTIFICATION_MESSAGE_LAST"

        val INITIAL_PARAMETERS_LIST : String = "INITIAL_PARAMETERS_LIST"
        val INITIAL_CITIES_LIST : String = "INITIAL_CITIES_LIST"
        val INITIAL_CITIES_LIST_IDS : String = "INITIAL_CITIES_LIST_IDS"
        val INITIAL_TYPE_QUERYS_LIST : String = "INITIAL_TYPE_QUERYS_LIST"
        val INITIAL_TYPE_QUERYS_IDS : String = "INITIAL_TYPE_QUERYS_IDS"

        val AWARD_PRODUCT_ID : String = "AWARD_PRODUCT_ID"
        val AWARD_BRANCH_SELECTED : String = "AWARD_BRANCH_SELECTED"
        val AWARD_KEY_BAUCHER : String = "AWARD_KEY_BAUCHER"
        val AWARD_KEY_COMPROBANT : String = "AWARD_KEY_COMPROBANT"


        val PARAM_ID_TELF_NATIONAL = 7
        val PARAM_ID_TELF_INTERNATIONAL = 8
        val PARAM_ID_TELF_TERMS = 9

        val PARAM_ID_TELF_SCZ = 13
        val PARAM_ID_TELF_LPZ = 14
        val PARAM_ID_TELF_CBBA = 15

        val FCM_MESSAGE_CONTENT : String = "FCM_MESSAGE_CONTENT"
    }


}